Dev
liveasy97/transporterAppFlutter pull request #26
Opened 2021-06-11 18:58 UTC by uttkarshrastogi

created order.dart
created loadwidget.dart

2021-06-14 16:02 UTC, liveasy97 commented on lib/screens/orderScreens/order.dart
> +                    SizedBox(width: size_7),
this has to be replaced by space_3

2021-06-22 21:41 UTC, liveasy97 commented on lib/screens/PostLoadScreens/PostLoadScreenOne.dart
> +                                          ? Navigator.push(
Use Getx for route management

2021-06-22 21:47 UTC, liveasy97 commented on lib/screens/PostLoadScreens/PostLoadScreenTwo.dart
> +                                            "abc",
loadingPoint is the field that contains the whole address of loading point so for now, pass "$LoadingPointCity, $LoadingPointState" here and same for unloadingPoint

2021-06-22 21:52 UTC, liveasy97 commented on lib/screens/orderScreens/order.dart
> +                            ? Navigator.push(
here too and for the whole app use getx for route management

2021-06-22 21:59 UTC, liveasy97 commented on lib/widgets/OrderTitleTextWidget.dart
> +class OrderTitleTextWidget extends StatelessWidget {
there is already a widget with these details named headingTextWidget.dart

2021-06-22 22:01 UTC, liveasy97 commented on lib/widgets/PostLoadScreenTwoSearch.dart
> +                  crossAxisCount: size_1.toInt(),
don't use size here may cause some issues later

2021-06-22 22:05 UTC, liveasy97 commented on lib/functions/PostLoadApi.dart
> +      "status": "On-going",
don't give status as a param its not needed here.

2021-06-22 22:06 UTC, liveasy97 commented on lib/functions/PostLoadApi.dart
> +    final response = await http.post(Uri.parse("http://65.0.19.187:8080/load"),
use this from env file

2021-06-22 22:13 UTC, liveasy97 commented on lib/screens/findLoadScreen.dart
> +                  HelpButtonWidget(),
there are few changes in this file that are unwanted. So paste this file from dev and just rename the variables

2021-06-23 19:24 UTC, uttkarshrastogi commented on lib/screens/findLoadScreen.dart
> +                  HelpButtonWidget(),
done

2021-06-23 19:24 UTC, uttkarshrastogi commented on lib/functions/PostLoadApi.dart
> +    final response = await http.post(Uri.parse("http://65.0.19.187:8080/load"),
done

2021-06-23 19:24 UTC, uttkarshrastogi commented on lib/functions/PostLoadApi.dart
> +      "status": "On-going",
done

2021-06-23 19:24 UTC, uttkarshrastogi commented on lib/screens/orderScreens/order.dart
> +                    SizedBox(width: size_7),
done

2021-06-23 19:24 UTC, uttkarshrastogi commented on lib/screens/PostLoadScreens/PostLoadScreenOne.dart
> +                                          ? Navigator.push(
done

2021-06-23 19:24 UTC, uttkarshrastogi commented on lib/screens/PostLoadScreens/PostLoadScreenTwo.dart
> +                                            "abc",
done

2021-06-23 19:24 UTC, uttkarshrastogi commented on lib/screens/orderScreens/order.dart
> +                            ? Navigator.push(
done

2021-06-23 19:24 UTC, uttkarshrastogi commented on lib/widgets/OrderTitleTextWidget.dart
> +class OrderTitleTextWidget extends StatelessWidget {
done

2021-06-23 19:24 UTC, uttkarshrastogi commented on lib/widgets/PostLoadScreenTwoSearch.dart
> +                  crossAxisCount: size_1.toInt(),
done

2021-06-23 19:25 UTC, uttkarshrastogi commented on lib/functions/PostLoadApi.dart
> +      "status": "On-going",
done

2021-06-23 19:25 UTC, uttkarshrastogi commented on lib/screens/findLoadScreen.dart
> +                  HelpButtonWidget(),
done

2021-06-23 19:25 UTC, uttkarshrastogi commented on lib/functions/PostLoadApi.dart
> +    final response = await http.post(Uri.parse("http://65.0.19.187:8080/load"),
done

2021-06-30 07:22 UTC, Atharv-Joshi commented on lib/screens/PostLoadScreens/PostLoadScreenOne.dart
> +import 'package:flutter/material.dart';
try to give this file  another name that describes its contents

2021-06-30 07:22 UTC, Atharv-Joshi commented on lib/screens/PostLoadScreens/PostLoadScreenTwo.dart
> +import 'package:flutter/cupertino.dart';
try to give this file name which describes its contents

2021-06-30 07:27 UTC, Atharv-Joshi commented on lib/screens/TruckScreens/myTrucksScreen.dart
> -
I guess the init function got deleted during merge , include this or the cards wont be generated

2021-06-30 07:30 UTC, Atharv-Joshi commented on lib/screens/postLoadScreens/postLoadScreen.dart
> +                  Positioned(bottom: space_3, child: PostButtonLoad())
This button isn't correctly positioned on the page

2021-06-30 07:35 UTC, Atharv-Joshi requested changes
init function in myTrucksScreen , Positioning of postLoadButton and renaming of few files(though not a priority)

2021-06-30 14:42 UTC, uttkarshrastogi commented on lib/screens/PostLoadScreens/PostLoadScreenOne.dart
> +import 'package:flutter/material.dart';
done

2021-06-30 14:42 UTC, uttkarshrastogi commented on lib/screens/PostLoadScreens/PostLoadScreenTwo.dart
> +import 'package:flutter/cupertino.dart';
done

2021-07-01 04:51 UTC, Atharv-Joshi commented on lib/screens/TransporterOrders/DeliveredScreenOrders/deliveredScreenOrders.dart
> +          future: bookingApiCalls.getDataByPostLoadIdDelivered(),
I wrote  that class for shipper side calls so the default param is postLoadId
Since you are writing transporter Side you have to pass param as transporterId
now you can either create a new class and hardcode transporterId or generalize the function you've used right now

2021-07-01 05:20 UTC, Atharv-Joshi commented on lib/screens/myLoadPages/onGoingScreen.dart
> +                future: bookingApiCalls.getDataByPostLoadIdOnGoing(),
Here too this function is for shipper side

2021-07-01 05:24 UTC, Atharv-Joshi requested changes
See the comment on deliveredScreenOrders

2021-07-01 05:41 UTC, Atharv-Joshi approved these changes

2021-07-02 09:26 UTC, liveasy97 approved these changes

2021-07-02 09:26 UTC, merged