Invoice Screen: UI Enhancement and PDF Upload Feature
liveasy97/transporterAppFlutter pull request #279
Opened 2024-01-30 07:51 UTC by TejasDhole

Invoice Screen:
1.check invoice ui
2.can see muliple img wil miniature view
3.reduce code reduncy 
4.updated color to used from color file
5.pull to reefresh feature added 
3.added refresh on clicking invocie screen 
7.added skelaton view for the table (shimmer)

Add Invocie Screen 
1.upgraded uplaod bill ui
2.fixed upload invoice bill in pdf format and convert into img byte and post api
3.fixed the insuuee to send multiple pages from pdf
4 added skelaton view in table (shiimmer)

2024-02-03 16:12 UTC, Anik-Chakraborty commented
![image](https://github.com/liveasy97/transporterAppFlutter/assets/79321628/1cce3c54-afde-473c-b0af-4c558c495163)
Browse file is not opening any window to pick files.

2024-02-03 16:22 UTC, Anik-Chakraborty requested changes

2024-02-03 16:22 UTC, Anik-Chakraborty commented on lib/functions/documentApi/postDocumentApiCall.dart
>      //     {"documentType": documentType, "data": photo64code}
Remove such commented codes.

2024-02-03 16:22 UTC, Anik-Chakraborty commented on lib/functions/documentApi/postDocumentApiCall.dart
> +    // print(response.body);
Here also

2024-02-03 16:22 UTC, Anik-Chakraborty commented on lib/functions/invoiceApi/invoiceApiService.dart
> +      // debugPrint('Error Response Body: ${response.body}');
..

2024-02-03 16:22 UTC, Anik-Chakraborty commented on lib/functions/invoiceApi/invoiceApiService.dart
> +        // print('Invoice created successfully! Invoice ID: $invoiceId');
..

2024-02-03 16:22 UTC, Anik-Chakraborty commented on lib/screens/invoiceScreens/InvoiceScreen.dart
> +            (index) => Container(
The same widget is present on add_invoice_screen.dart file... so reuse it...and define it in a  widget directory

2024-02-04 07:09 UTC, TejasDhole commented on lib/functions/documentApi/postDocumentApiCall.dart
>      //     {"documentType": documentType, "data": photo64code}
This code was added by another developer, and its purpose isn't clear to me.
 I considered removing it during development, but I wasn't aware of its potential use in the future
 Please review and decide whether to keep, modify, or remove this code based on its original purpose.

2024-02-04 15:47 UTC, Anik-Chakraborty approved these changes

2024-02-05 04:51 UTC, merged